"""Updated films schema

Revision ID: 1ba955b73ea3
Revises: 1d13a703db46
Create Date: 2026-08-18 17:17:52.037243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba955b73ea3'
down_revision: Union[str, Sequence[str], None] = '1d13a703db46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'overview',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'tagline',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('films', 'tagline',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'overview',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
