"""Updated films schema

Revision ID: 1d13a703db46
Revises: 4ef1064f8b05
Create Date: 2026-08-18 16:03:14.297646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d13a703db46'
down_revision: Union[str, Sequence[str], None] = '4ef1064f8b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'genres',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False)
    op.alter_column('films', 'overview',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'tagline',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('films', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('films', 'tagline',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'overview',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('films', 'genres',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=False)
    # ### end Alembic commands ###
