"""Updated films model schema

Revision ID: 627d3dd9f895
Revises: 1ba955b73ea3
Create Date: 2026-10-03 23:17:24.644082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '627d3dd9f895'
down_revision: Union[str, Sequence[str], None] = '1ba955b73ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_genres',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'genre_id')
    )
    op.add_column('films', sa.Column('original_title', sa.String(), nullable=False))
    op.add_column('films', sa.Column('release_year', sa.Integer(), nullable=False))
    op.add_column('films', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=False))
    op.drop_column('films', 'budget')
    op.drop_column('films', 'release_date')
    op.drop_column('films', 'tagline')
    op.drop_column('films', 'production_companies')
    op.drop_column('films', 'runtime')
    op.drop_column('films', 'genres')
    op.drop_column('films', 'tmdb_id')
    op.drop_column('films', 'revenue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('runtime', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('production_companies', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('tagline', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('films', sa.Column('budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('films', 'embedding')
    op.drop_column('films', 'release_year')
    op.drop_column('films', 'original_title')
    op.drop_table('film_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
