[project]
name = "besttea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.1",
    "mlflow>=3.16.0",
    "numpy>=2.5.2",
    "optuna>=4.9.0",
    "pandas>=3.0.5",
    "pgvector>=0.5.0",
    "pydantic-settings>=2.15.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "sentence-transformers>=6.1.0",
]
